### PR TITLE
replace reltool with relx

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by essen** [comment]
You probably didn't want to commit the .app.src and .erl with the upgrade changes.

**Comment by tsloughter** [comment]
Argh, yeah. And realized there is a part of the start script I forgot to
change. Fixing.

**Comment by tsloughter** [comment]
Updated

**Comment by essen** [comment]
relcool can't do upgrades?

**Comment by tsloughter** [comment]
No, it doesn't handle upgrades yet. Looking into that now. Let me know if
you have any suggestions. We'll want to also make it easy to use without
rebar as well.

**Comment by essen** [comment]
I got no idea how generating upgrades work at this point.

**Comment by essen** [comment]
I think relcool is in a good enough state for this to be merged now. But the PR needs heavy fixing and should probably use most of relcool generated files.

**Comment by essen** [comment]
Wait, my memory might be fuzzy, are upgrades in yet?

**Comment by tsloughter** [comment]
Stilll no upgrades.

**Comment by essen** [comment]
So since we have upgrades now you may want to update your patch. :)

**Comment by essen** [comment]
Think of all the good you'll do when you update this patch! You know you can't resist. :)

**Comment by tsloughter** [comment]
Fine! ;)

**Comment by essen** [comment]
You pushed things but it says I can't merge and I don't think you changed anything.

**Comment by tsloughter** [comment]
What about now? (I haven't tested it)

**Comment by essen** [comment]
You didn't update the readme so I have no idea how to test this.

**Comment by tsloughter** [comment]
Updated. Should work as it did before now.

**Comment by tsloughter** [comment]
Dammit. Nevermind. Still more to fix.

**Comment by essen** [comment]
Dammit!

**Comment by essen** [comment]
Still more to fix?

**Comment by essen** [comment]
Hello?

**Comment by tsloughter** [comment]
Hmm, I never finished this? Hehe, will try to remember to do it today. Maybe just need to push.

**Comment by essen** [comment]
Well I got no idea what's left to fix so I hope you remember. :)

**Comment by tsloughter** [comment]
Updated again.

**Comment by essen** [comment]
Woot woot!

**Pull request merged**
